Завершаем вёрстку всех компонентов
htmlacademy-htmlcss/1982775-sedona-34 pull request #10
Opened 2022-07-07 13:03 UTC by Geozoyka

Не могу разобраться что не так, в каталоге, валидатор ругается на 204 строку.
*Обрати также внимание на 113 строку CSS.
*И ещё в каталоге в инпуте над ползунком с состоянии active рамка как то не так отображается.
Пожалуйста поясни что делать дальше.

---
:mortar_board: [Завершаем вёрстку всех компонентов](https://up.htmlacademy.ru/htmlcss/34/user/1982775/tasks/11)

:boom: https://htmlacademy-htmlcss.github.io/1982775-sedona-34/10/

2022-07-07 20:26 UTC, Zakamsky requested changes
спасибо за вопросы, давай разбересмя:

> - валидатор ругается на 204 строку

Сама ошибка указщывает нам что `legend` не может быть потомком`form`, этот тэг можно разместить только в `fieldset` и только первым ребенком.
но проблема у нас даже не в этом.
не могу тебе сейчас показать комментами в штмл файле, т.к. не могу выделитть строки без правок (видимо я давно просмотрел). давай скриншотом:
![image](https://user-images.githubusercontent.com/35491086/177858692-00a28c69-1c88-4e5a-95c7-5464f0baaf0b.png)
у тебя есть форма которая закрыта раньше времени, далее идет ворая форма, которую надо просто заменить на `fieldset` но основную форму надо закрыть не там где она закрыта сейчас, а перед закрывающим тэгом, оберткой формы (после блока с кнопками).
дело в том что в текущей реализации форму невозможно отправить, и да, это одна большая форма, а не несколько маленьких. просто попробуй отправить форму.

> Обрати также внимание на 113 строку CSS.
ты прав, это сомнительное решение.
можно сделать вот так:
![image](https://user-images.githubusercontent.com/35491086/177860151-8423ad45-dbbf-43c0-a392-a055a0bf228b.png)
но я там кроме того что видно еще поменял левый отступ у кнопки:
![image](https://user-images.githubusercontent.com/35491086/177860336-dfae1403-2eb0-4d54-81d5-e0a49dc6cc2c.png)

> в каталоге в инпуте над ползунком с состоянии active рамка как то не так отображается.

Дело в том что в момент клика инпут автоматически получает фокус и применяются его стили. Это нормально.
Но для фокуса в макете еще предусмотрена внутренняя тень такая же как внешняя (несколько теней просто пишутся через запятую.)

кроме того, вот тут поломан макет, можно просто добавить пробел мнемоником:
![image](https://user-images.githubusercontent.com/35491086/177861173-92975729-9b75-4e6f-a892-1a29a7ba166b.png)

тут ты задал ширину паддингом и с широким содержимым блоки стали больше макета, я убавляю паддинг до минимально симпатичного и задаю минимальную ширину.
(c `box-sizing: border-box` это было бы удобнее)
![image](https://user-images.githubusercontent.com/35491086/177861804-db5b2d81-10f7-4a7c-9fd1-8d88496bb888.png)

В остальном я давно не видел такого отличного ПП.

дорабатывай, пробегись самостоятельно по критериям и можно на защиту!

2022-07-07 20:26 UTC, Zakamsky commented on styles/styles.css
> +}
Если тут все отлично и корректно - мы выбираем `.control-mark` который внутри `.control:hover`
то ниже начнутся проблемы.

2022-07-07 20:26 UTC, Zakamsky commented on styles/styles.css
> +}
`.control` это лэйбл, у него нет фокуса и актива, мы могли бы еще найти фокус внутри ( `:focus-inside` ) но с активом это не сработает.

поэтому тут надо работать с фокусом и активом инпута, так же как с чеком работаем:
`.control-input:focus + .control-mark`  (эй браузер, найди ка нам `.control-mark` перед которым в потоке  `.control-input' с состоянием ':focus' )

2022-07-07 20:26 UTC, Zakamsky commented on styles/styles.css
> +  position: fixed;
отличное решение, сразу видно в отладчике какой дисплэй нужен.
но можно сделать немного лучше:
1. тут оставляем только `display: flex;`
2. форме добавляем класс `hidden`
3. ниже пишем:
```css
.modal-container.hidden {
  display: none;
}
```
получается не менее очевидный вариант и готовый под оживление - скрипт будет по клику убирать этот класс, а по клику на крестик добавлять.

2022-07-07 20:26 UTC, Zakamsky commented on styles/styles.css
> +}
супер, теперь давай подумаем. мы не можем без скрипта узнать совпадает ли дата с текущей (не прошла ли она) и есть ли места.
значит скрипт будет добавлять классы к полям.
предположим для прошлого будет класс - `.past-invalid` а для доступных дат - `.available-date` 
пишем их инпутам `.modal-input`
и так как тексты лежат сразу после инпутов используем селектор ближайшего соседа: +
```css
.modal-input.available-date + .note-exit,
.modal-input.past-invalid + .note-entry{
  display: block; /* или какой нам нужно */
}
```

2022-07-09 14:55 UTC, Geozoyka commented on styles/styles.css
> +}
Извини Я ничего тут не понял

2022-07-09 14:56 UTC, Geozoyka commented on styles/styles.css
> +}
И тут не понял, сложновато

2022-07-09 15:12 UTC, Geozoyka commented on styles/styles.css
> +}
Тут тоже с трудом понимаю. Поясни пожалуйста это ( display: block; /* или какой нам нужно */)

2022-07-09 16:16 UTC, Zakamsky commented on styles/styles.css
> +}
это предисловие, к следующему комменту.

2022-07-09 16:32 UTC, Zakamsky commented on styles/styles.css
> +}
я пишу `display: block;`, но возможно нам нужен `display: flex;`

2022-07-10 15:09 UTC, Geozoyka commented on styles/styles.css
> +}
Вроде сделал

2022-07-10 19:45 UTC, Zakamsky approved these changes
Отлично все, ты хорошо постарался и разобрался во селекторах!
немного надо подшаманить форму.
давай я уже приму, поправь форму, пробегись сам по критериям и присылай на защиту.
я там еще раз проверю все и дам допуск.

2022-07-10 19:45 UTC, Zakamsky commented on index.html
> +                  <button class="quantity-btn quantity-up"></button>
Эти кнопки сабмитят форму, возможно ты не заметил, потому что форма не работает - не указаны нужные атрибуты.
а инпутам неплохо бы добавить плэйсхолдеры с нужными числами.
так же у кнопок нет никаких подписей...

2022-07-10 19:46 UTC, merged