Базовая стилизация
htmlacademy-htmlcss/1982775-sedona-34 pull request #5
Opened 2022-06-06 13:37 UTC by Geozoyka

Подключил в CSS, шрифты и изображения

2022-06-06 22:20 UTC, Zakamsky requested changes
Очень добротное исполнение, на 4 с плюсом. Я в целом даже думал принять но боюсь что мелочевка потеряется в следующем задании...
давай дошлифуем!
Постарался к каждой строке комментарии написать максимально подробно.
Если будет непонятно что то - спрашивай смело. Только пожалуйста собери все вопросы разом, что бы я сел и на все сразу ответил.

2022-06-06 22:20 UTC, Zakamsky commented on catalog.html
> +        <a class="logo" href="catalog.html"
Вот тут все корректно было, ты возможно страницы перепутал и смысл ссылки?
В общем с логотипа обычно ссылка всегда ведет на главную, но никак ни на текущую страницу...

2022-06-06 22:20 UTC, Zakamsky commented on catalog.html
> +              >Главная</a
Да похоже что перепутал страницы, тут бы нам надо ссылку на главную и убрать класс navigation-link-current т.к. мы на другой странице.

p.s. Вообще сейчас считается лучшей практикой оставлять ссылку даже если она ведет сама на себя (на текущую страницу, с главной на главную), но для разборчивости скрин ридерам добавлять атрибут `aria-current="pge"`

2022-06-06 22:20 UTC, Zakamsky commented on catalog.html
>              </button>
Эта кнопка не должна иметь `type="submit"` какую форму она отправляет? просто `type="button"` что бы привести в действие скрипт (мифический) без лишних последствий.

на счет отдельного цвета идея такая:
- одной кнопке (или сколько их в макете?) мы для демонстрации задаем дополнительный класс, например `.product-card-selected`  и текст "В избранном"
- в стилях прописываем для этого класса зеленый фон.
потом программист или мы сами напишем скрипт (в теории, почему я выше назвал его - "мифический") который будет слушать нажатие кнопки, и по нему предавать данные на сервер и добавлять кнопке этот класс и менять в ней текст на этот.

2022-06-06 22:20 UTC, Zakamsky commented on catalog.html
> +      </div>
добавив этот див ты где то потерял закрывающий тэг секции... посмотри в валидаторе он подсвечивает, но в таких случаях он часто ошибается т.к. не знает какой из тэгов ошибочный.
Если сам не найдешь как поправить - напиши разберемся.
(можно глянуть версии в гите как там была секция ранее сделана)

2022-06-06 22:20 UTC, Zakamsky commented on styles/styles.css
> +  font-family: "PT Sans", sans-serif;
Это свойство наследуется т.ч. хорошо что ты не задал его в в каждый тэг, но все же почти все элементы форм и кнопки не наследуют шрифты (у них есть свои стили шрифта по умолчанию) и им стоит их указать отдельно. (где нужно)

2022-06-06 22:20 UTC, Zakamsky commented on styles/styles.css
> +  display: none;
Здорово что ты разобрался и взял в проект рабочий `.visually-hidden` только надо удалить закомментированную строку, она устарела для наших проектов.
и `display: none;` полностью убивает доступность, т.е. все ради чего существует этот класс, это тоже нужно убрать.

2022-06-06 22:20 UTC, Zakamsky commented on styles/styles.css
> +  background-image: url("../images/index-background.jpg");
прямо супер что ты в каждый фон добавил цвет по умолчанию, все об этом вечно забывают!
з.ы. возможно именно  в этом месте можно взять цвет посветлее т.к. этот цвет совпадает с одним из слов слогана =)

2022-06-06 22:20 UTC, Zakamsky commented on styles/styles.css
> +} */
тут можно не повторять все стили а оставить только то что отличается:
```css
.product-card-selected {
  background: #7DB54F;
}
```
и уже включить его, просто оставить сам класс только на нужной кнопке.

2022-06-06 22:20 UTC, Zakamsky commented on styles/styles.css
> +}
кстати вендорные стили границы еще стоит сбросить.

2022-06-06 22:20 UTC, Zakamsky commented on catalog.html
> +                    <input
вот у тебя есть ведь класс `.control` почему по нему не стилизовать текст лэйбла?
или что у тебя не получалось стилизовать? я не понял...

2022-06-08 08:37 UTC, Geozoyka commented on catalog.html
>              </button>
Приветик.
Просто убрать submit или вместе с type?

2022-06-08 08:38 UTC, Geozoyka commented on catalog.html
> +        <a class="logo" href="catalog.html"
сделал

2022-06-08 08:41 UTC, Geozoyka commented on catalog.html
> +              >Главная</a
насчёт aria-current="pge" надеюсь правильно вставил (никогда не слышал о нём)

2022-06-08 08:49 UTC, Geozoyka commented on styles/styles.css
> +  display: none;
сделал

2022-06-08 08:54 UTC, Geozoyka commented on styles/styles.css
> +  background-image: url("../images/index-background.jpg");
Сделал по светлее, правда я что то не нашёл где он совпадает по цвету

2022-06-08 08:59 UTC, Geozoyka commented on styles/styles.css
> +} */
Сделал

2022-06-08 09:00 UTC, Geozoyka commented on styles/styles.css
> +}
Не понял рекомендацию. Пожалуйста поясняй термины.

2022-06-08 09:12 UTC, Geozoyka commented on catalog.html
> +                    <input
сделал.

2022-06-08 09:20 UTC, Geozoyka commented on catalog.html
> +              >Главная</a
На aria-current="pge" валидатор ругается. <a class="navigation-link" aria-current="pge" href="index.html"
              >Главная</a Объясни пожалуйста куда его вставлять

2022-06-08 09:46 UTC, Geozoyka commented on catalog.html
> +      </div>
Кое что поправил но валидатор всё равно ругается на </section>

2022-06-08 11:04 UTC, Zakamsky commented on catalog.html
> +              >Главная</a
тут ничего сверхъестественного:
```html
<a href="index.html" aria-current="page" class="nav-link">главная</a>
```
Как любые атрибуты.
p.s. блииин.... у меня в комментарии опечатка, прошу прощения, конечно же:  `aria-current="page"`

2022-06-08 11:07 UTC, Zakamsky commented on catalog.html
>              </button>
Мы не можем ни просто убрать этот атрибут, ни оставить пустым.
первое приведет к использованию значения по умолчанию, а оно такое же.
(это редкое исключение из правил когда мы пишем руками значение по умолчанию, что бы было максимально очевидно что используется, вот как сейчас.)

в данном случае стоит использовать `type="button"`
```html
<button class="product-card-favorit product-card-selected" type="button">
```

2022-06-08 11:19 UTC, Zakamsky commented on styles/styles.css
> +}
отличный вопрос, напишу в чате об этом.

2022-06-08 13:32 UTC, Zakamsky approved these changes
Добротная работа над ошибками, разобрались со всем, не забудь про список карточек пожалуйста.

2022-06-08 13:32 UTC, merged