8. Декоративные элементы
htmlacademy-htmlcss/1982775-sedona-34 pull request #9
Opened 2022-06-25 14:37 UTC by Geozoyka

Заменил некоторые иконки на svg.
Присвоил состояния почти всем элементам.
Отсылаю на предварительную проверку. Мозг надо перезагрузить, и необходим твой свежий взгляд

2022-06-27 19:13 UTC, Zakamsky requested changes
Замечания, как ты просил, написал, в целом неплохо.

2022-06-27 19:13 UTC, Zakamsky commented on catalog.html
> +                  tabindex="0"
Я видимо плохо объяснял, это был пример как делать НЕнужно.
Пожалуйста убери все табиндексы с `svg` и сделай состояния как у тебя сделано в подвале.
в данном случае это должно выглядеть так:
.navigation-link:hover > .navigation-icon { ... }

2022-06-27 19:13 UTC, Zakamsky commented on index.html
> +              <a class="navigation-link navigation-link-current-main" href="#"
тут бы тоже атрибут `aria-current` добавить, это ведь ссылка прямо на эту страницу.

2022-06-27 19:13 UTC, Zakamsky commented on catalog.html
> +          <a class="logo" href="index.html" aria-current="page"
в данном контексте ссылка ведет с этой страницы (каталога) на другую (главную), т.е. `aria-current="page"` тут лишний.
Его надо добавить логотипу только на главной, где ссылка будет вести на саму себя.
На это странице стоит добавить такой атрибут для ссылки на каталог в меню.
Попробуй так - если название файла и адрес в хреф совпадают - надо добавить этот атрибут.

2022-06-27 19:13 UTC, Zakamsky commented on styles/styles.css
> +}
тут у тебя путаница, на 644й строке (не могу выделить то что не менялось)
там не нужно указывать оба класса, только основной.
и потом в штмл убери класс `.product-card-selected` со всех кнопок кроме одной.
а все стили этого класса должны быть ниже стилей `.product-card-favorit` тогда все будет работать хорошо.

2022-06-28 12:06 UTC, Geozoyka commented on styles/styles.css
> +}
Тут не совсем понял, но вроде сделал. Однако мне не понятно кнопка В ИЗБРАННОМ может ведь стать любая кнопка, почему тогда мы удираем класс .product-card-selected с остальных кнопок?

2022-06-29 14:07 UTC, Zakamsky approved these changes
Вот теперь прямо отлично, остались формы и попап.

2022-06-29 14:07 UTC, merged

2022-06-29 14:42 UTC, Zakamsky commented on styles/styles.css
> +}
Мы как раз имитируем работу скрипта.
Наша задача такая - любая кнопка у которой появится этот класс - должна стать зеленой, включая все состояния. А та у которой нет такого класса - обычной.
Поэтому у нас не должно быть класса на всех элементах, что бы было видно как он работает.

И на проверке обязательно этот класс будут подставлять руками в отладчике и смотреть как работает.